namespace Tally.Models;

/// <summary>
/// Starter list of drinks (carried over from the old HTML version).
/// Only used on the very first launch, or via "Add default articles".
/// </summary>
public static class DefaultArticles
{
    public static readonly string[] DefaultCategories =
    {
        "Bier", "Wein", "Spirituosen", "Softdrinks", "Snacks", "Sonstiges"
    };

    public static readonly (string Name, string Category)[] All =
    {
        ("Astra Rakete", "Bier"),
        ("Benediktiner Weissbier", "Bier"),
        ("Bitburger Premium Pils", "Bier"),
        ("Budweiser Budvar", "Bier"),
        ("Carlsberg Beer", "Bier"),
        ("Diebels Alt", "Bier"),
        ("Duckstein Original", "Bier"),
        ("Einbecker Mai-Urbock", "Bier"),
        ("Franziskaner Alkoholfrei", "Bier"),
        ("Grevensteiner Original", "Bier"),
        ("Hacker-Pschorr Münchner Hell", "Bier"),
        ("Hasen-Bräu Extra Hell", "Bier"),
        ("Holsten Pilsener", "Bier"),
        ("König Pilsener", "Bier"),
        ("Köstritzer Schwarzbier", "Bier"),
        ("Krombacher Radler", "Bier"),
        ("Leffe Blond", "Bier"),
        ("Leffe Brune", "Bier"),
        ("Maisel's Weisse Original", "Bier"),
        ("Miller Genuine Draft", "Bier"),
        ("Mönchshof Landbier", "Bier"),
        ("Oettinger Pils", "Bier"),
        ("Paulaner Münchner Hell", "Bier"),
        ("Peroni Nastro Azzurro", "Bier"),
        ("Pilsner Urquell", "Bier"),
        ("Reissdorf Kölsch", "Bier"),
        ("San Miguel Spezial", "Bier"),
        ("Schlösser Alt", "Bier"),
        ("Schöfferhofer Weizen Hell", "Bier"),
        ("Schultheiss Pilsener", "Bier"),
        ("Staropramen Premium", "Bier"),
        ("Stella Artois", "Bier"),
        ("Störtebeker Atlantik-Ale", "Bier"),
        ("Ur-Krostitzer Pilsner", "Bier"),
        ("Früh Kölsch", "Bier"),
        ("7UP", "Softdrinks"),
        ("Almdudler", "Softdrinks"),
        ("Bionade Holunder", "Softdrinks"),
        ("Bionade Kräuter", "Softdrinks"),
        ("Coca-Cola Light", "Softdrinks"),
        ("Dr Pepper", "Softdrinks"),
        ("Fanta Exotic", "Softdrinks"),
        ("Fritz-Kola", "Softdrinks"),
        ("Fritz-Limo Zitrone", "Softdrinks"),
        ("Fritz-Limo Orange", "Softdrinks"),
        ("Gatorade Cool Blue", "Softdrinks"),
        ("Libella Zitronenlimonade", "Softdrinks"),
        ("Lipton Eistee Pfirsich", "Softdrinks"),
        ("Lipton Eistee Zitrone", "Softdrinks"),
        ("Mio Mio Mate", "Softdrinks"),
        ("Monster Energy Ultra White", "Softdrinks"),
        ("Mountain Dew", "Softdrinks"),
        ("Orangina Original", "Softdrinks"),
        ("Red Bull Sugarfree", "Softdrinks"),
        ("Red Bull Summer Edition", "Softdrinks"),
        ("Relentless Energy", "Softdrinks"),
        ("San Pellegrino Aranciata", "Softdrinks"),
        ("San Pellegrino Limonata", "Softdrinks"),
        ("Schweppes Wild Berry", "Softdrinks"),
        ("Sprite Zero", "Softdrinks"),
        ("Thomas Henry Spicy Ginger", "Softdrinks"),
        ("Thomas Henry Wild Berry", "Softdrinks"),
        ("Vita Cola", "Softdrinks"),
        ("Volvic Touch Zitrone", "Softdrinks"),
        ("Apollinaris Classic", "Softdrinks"),
        ("Evian Still", "Softdrinks"),
        ("Fachingen Medium", "Softdrinks"),
        ("Lichtenauer Mineralwasser", "Softdrinks"),
        ("Rheinfels Quelle Medium", "Softdrinks"),
        ("Rhönsprudel Original", "Softdrinks"),
        ("Vittel Mineralwasser", "Softdrinks"),
        ("Granini Bananensaft", "Softdrinks"),
        ("Granini Kirschnektar", "Softdrinks"),
        ("Granini Multivitaminsaft", "Softdrinks"),
        ("Granini Tomatensaft", "Softdrinks"),
        ("Hohes C Orange", "Softdrinks"),
        ("Hohes C Milder Apfel", "Softdrinks"),
        ("Klindworth Apfelsaft", "Softdrinks"),
        ("Rauch Happy Day Erdbeere", "Softdrinks"),
        ("Rauch Happy Day Mango", "Softdrinks"),
        ("Rauch Happy Day Rhabarber", "Softdrinks"),
        ("Albi Johannisbeernektar", "Softdrinks"),
        ("Beckers Bester Apfelsaft", "Softdrinks"),
        ("Beckers Bester Orangensaft", "Softdrinks"),
        ("Innocent Orangensaft", "Softdrinks"),
        ("Valensina Frühstücksorange", "Softdrinks"),
        ("Pfanner Eistee Pfirsich", "Softdrinks"),
        ("Pfanner Eistee Zitrone", "Softdrinks"),
        ("Fuze Tea Zitrone", "Softdrinks"),
        ("Cîroc Vodka", "Spirituosen"),
        ("Crystal Head Vodka", "Spirituosen"),
        ("Ketel One Vodka", "Spirituosen"),
        ("Skyy Vodka", "Spirituosen"),
        ("Stolichnaya Vodka", "Spirituosen"),
        ("Tito's Handmade Vodka", "Spirituosen"),
        ("Wodka Partisan", "Spirituosen"),
        ("Zubrowka Bison Grass Vodka", "Spirituosen"),
        ("9 Mile Vodka", "Spirituosen"),
        ("Bazic Vodka", "Spirituosen"),
        ("Kauffman Vodka", "Spirituosen"),
        ("Nemiroff De Luxe Vodka", "Spirituosen"),
        ("Pravda Vodka", "Spirituosen"),
        ("Royal Dragon Vodka", "Spirituosen"),
        ("Snow Leopard Vodka", "Spirituosen"),
        ("Stoli Elit Vodka", "Spirituosen"),
        ("Aberlour 12 Jahre", "Spirituosen"),
        ("Ardbeg 10 Jahre", "Spirituosen"),
        ("Bowmore 12 Jahre", "Spirituosen"),
        ("Bulleit Bourbon", "Spirituosen"),
        ("Bushmills Original", "Spirituosen"),
        ("Canadian Club", "Spirituosen"),
        ("Dalwhinnie 15 Jahre", "Spirituosen"),
        ("Highland Park 12 Jahre", "Spirituosen"),
        ("Laphroaig 10 Jahre", "Spirituosen"),
        ("Lagavulin 16 Jahre", "Spirituosen"),
        ("Macallan 12 Jahre Double Cask", "Spirituosen"),
        ("Monkey Shoulder Scotch Whisky", "Spirituosen"),
        ("Oban 14 Jahre", "Spirituosen"),
        ("Redbreast 12 Jahre", "Spirituosen"),
        ("Southern Comfort", "Spirituosen"),
        ("Talisker 10 Jahre", "Spirituosen"),
        ("Wild Turkey 101 Bourbon", "Spirituosen"),
        ("Woodford Reserve Bourbon", "Spirituosen"),
        ("Akashi Meisei Whisky", "Spirituosen"),
        ("Nikka From The Barrel Whisky", "Spirituosen"),
        ("Appleton Estate Signature", "Spirituosen"),
        ("Bumbu Rum", "Spirituosen"),
        ("Diplomatico Mantuano", "Spirituosen"),
        ("El Dorado 12 Jahre", "Spirituosen"),
        ("Gosling's Black Seal Rum", "Spirituosen"),
        ("Kraken Black Spiced Rum", "Spirituosen"),
        ("Mount Gay Eclipse Rum", "Spirituosen"),
        ("Myers's Rum Original Dark", "Spirituosen"),
        ("Plantation 3 Stars White Rum", "Spirituosen"),
        ("Plantation Grande Reserve Rum", "Spirituosen"),
        ("Pyrat XO Reserve Rum", "Spirituosen"),
        ("Ron Abuelo 12 Años", "Spirituosen"),
        ("Ron Barceló Imperial", "Spirituosen"),
        ("Ron Botran Reserva 15", "Spirituosen"),
        ("Ron Centenario 20 Jahre", "Spirituosen"),
        ("Ron Matusalem Gran Reserva 15", "Spirituosen"),
        ("Sailor Jerry Spiced Rum", "Spirituosen"),
        ("Stroh 80 Rum", "Spirituosen"),
        ("Stroh 54 Rum", "Spirituosen"),
        ("Takamaka Extra Noir Rum", "Spirituosen"),
        ("Aviation American Gin", "Spirituosen"),
        ("Beefeater London Dry Gin", "Spirituosen"),
        ("Gin Mare", "Spirituosen"),
        ("Malfy Gin Con Limone", "Spirituosen"),
        ("Malfy Gin Rosa", "Spirituosen"),
        ("Nordés Atlantic Galician Gin", "Spirituosen"),
        ("Plymouth Gin", "Spirituosen"),
        ("Roku Japanese Gin", "Spirituosen"),
        ("Sipsmith London Dry Gin", "Spirituosen"),
        ("Elephant Gin", "Spirituosen"),
        ("Friedrichs Dry Gin", "Spirituosen"),
        ("Generous Gin", "Spirituosen"),
        ("Hayman's London Dry Gin", "Spirituosen"),
        ("Jinzu Gin", "Spirituosen"),
        ("Le Tribute Gin", "Spirituosen"),
        ("Opihr Spiced London Dry Gin", "Spirituosen"),
        ("Siegfried Rheinland Dry Gin", "Spirituosen"),
        ("Windspiel Premium Dry Gin", "Spirituosen"),
        ("Brockmans Intensely Smooth Gin", "Spirituosen"),
        ("Whitley Neill Rhubarb & Ginger Gin", "Spirituosen"),
        ("1800 Añejo Tequila", "Spirituosen"),
        ("1800 Reposado Tequila", "Spirituosen"),
        ("Casamigos Blanco Tequila", "Spirituosen"),
        ("Casamigos Reposado Tequila", "Spirituosen"),
        ("Del Maguey Vida Mezcal", "Spirituosen"),
        ("Don Julio Reposado", "Spirituosen"),
        ("Espolòn Tequila Blanco", "Spirituosen"),
        ("Espolòn Tequila Reposado", "Spirituosen"),
        ("Herradura Plata Tequila", "Spirituosen"),
        ("Patron Silver Tequila", "Spirituosen"),
        ("Amaretto Disaronno", "Spirituosen"),
        ("Averna Amaro Siciliano", "Spirituosen"),
        ("Chartreuse Verte", "Spirituosen"),
        ("Cointreau", "Spirituosen"),
        ("Drambuie", "Spirituosen"),
        ("Frangelico", "Spirituosen"),
        ("Galliano L'Autentico", "Spirituosen"),
        ("Grand Marnier Cordon Rouge", "Spirituosen"),
        ("Kahlúa Kaffeelikör", "Spirituosen"),
        ("Licor 43", "Spirituosen"),
        ("Limoncello di Capri", "Spirituosen"),
        ("Pimm's No. 1", "Spirituosen"),
        ("Southern Comfort Black", "Spirituosen"),
        ("Unicum Kräuterlikör", "Spirituosen"),
        ("Kilkenny Red Ale", "Bier"),
        ("Büble Bayrisch Hell", "Bier"),
        ("Starnberger Helles", "Bier"),
        ("Bayreuther Hell", "Bier"),
        ("Chiemseer Hell", "Bier"),
        ("Spaten Münchner Hell", "Bier"),
        ("Löwenbräu Original", "Bier"),
        ("Hofbräu Original", "Bier"),
        ("Weihenstephaner Hefeweissbier", "Bier"),
        ("Maisel's Weisse", "Bier"),
        ("Gutmann Hefeweizen", "Bier"),
        ("Lübzer Pils", "Bier"),
        ("Hasseröder Premium Pils", "Bier"),
        ("Frankenheim Alt", "Bier"),
        ("Gaffel Kölsch", "Bier"),
        ("Schlosser Alt", "Bier"),
        ("Berliner Kindl Jubiläums Pilsener", "Bier"),
        ("Berliner Pilsner", "Bier"),
        ("Sternburg Export", "Bier"),
        ("Oettinger Export", "Bier"),
        ("Schlenkerla Rauchbier", "Bier"),
        ("San Miguel Especial", "Bier"),
        ("Estrella Damm", "Bier"),
        ("Birra Moretti", "Bier"),
        ("Budweiser Lager", "Bier"),
        ("Kozel Cerny", "Bier"),
        ("Carlsberg Elephant", "Bier"),
        ("Tuborg Green", "Bier"),
        ("Leffe Blonde", "Bier"),
        ("Hoegaarden Witbier", "Bier"),
        ("Chimay Red", "Bier"),
        ("Duvel Strong Ale", "Bier"),
        ("Salitos Ice", "Bier"),
        ("Schöfferhofer Weizen-Mix Zitrone", "Bier"),
        ("Bitburger Radler", "Bier"),
        ("Clausthaler Alkoholfrei", "Bier"),
        ("Coca-Cola Vanilla", "Softdrinks"),
        ("Fanta Zero", "Softdrinks"),
        ("Pepsi Cola", "Softdrinks"),
        ("Pepsi MAX", "Softdrinks"),
        ("Mirinda", "Softdrinks"),
        ("Lipton Ice Tea Lemon", "Softdrinks"),
        ("Lipton Ice Tea Peach", "Softdrinks"),
        ("Fuze Tea Pfirsich", "Softdrinks"),
        ("Arizona Iced Tea Green Tea", "Softdrinks"),
        ("Elephant Bay Watermelon", "Softdrinks"),
        ("Red Bull Edition Yellow", "Softdrinks"),
        ("Red Bull Edition Red", "Softdrinks"),
        ("Red Bull Edition Blue", "Softdrinks"),
        ("Rockstar Energy Original", "Softdrinks"),
        ("Monster Ultra White", "Softdrinks"),
        ("Schweppes Dry Tonic", "Softdrinks"),
        ("Thomas Henry Pink Grapefruit", "Softdrinks"),
        ("Fever-Tree Indian Tonic Water", "Softdrinks"),
        ("Fever-Tree Mediterranean Tonic", "Softdrinks"),
        ("Fever-Tree Ginger Beer", "Softdrinks"),
        ("Granini Apfelsaft", "Softdrinks"),
        ("Granini Orangensaft", "Softdrinks"),
        ("Granini Traubensaft", "Softdrinks"),
        ("Granini Rhabarbersaft", "Softdrinks"),
        ("Granini Mangosaft", "Softdrinks"),
        ("Beckers Bester Kirschnektar", "Softdrinks"),
        ("Beckers Bester Bananennektar", "Softdrinks"),
        ("RhönSprudel Mineralwasser", "Softdrinks"),
        ("Apollinaris Mineralwasser", "Softdrinks"),
        ("Evian Stilles Wasser", "Softdrinks"),
        ("Fiji Water", "Softdrinks"),
        ("Staatlich Fachingen", "Softdrinks"),
        ("Adelholzener Mineralwasser", "Softdrinks"),
        ("Moskovskaya Vodka", "Spirituosen"),
        ("Belvedere Intense", "Spirituosen"),
        ("Bushmills Original Irish Whiskey", "Spirituosen"),
        ("Kilbeggan Irish Whiskey", "Spirituosen"),
        ("Paddy Irish Whiskey", "Spirituosen"),
        ("Bulleit Rye", "Spirituosen"),
        ("Elijah Craig Small Batch", "Spirituosen"),
        ("Jack Daniel's Single Barrel", "Spirituosen"),
        ("Jack Daniel's Fire", "Spirituosen"),
        ("Jim Beam Black", "Spirituosen"),
        ("Johnnie Walker Gold Label", "Spirituosen"),
        ("Johnnie Walker Blue Label", "Spirituosen"),
        ("The Glenlivet 12 Jahre", "Spirituosen"),
        ("Captain Morgan White Rum", "Spirituosen"),
        ("Captain Morgan Black Spiced", "Spirituosen"),
        ("Bacardi Añejo Cuatro", "Spirituosen"),
        ("Bacardi Ocho 8 Años", "Spirituosen"),
        ("Havana Club Especial", "Spirituosen"),
        ("Havana Club Selección de Maestros", "Spirituosen"),
        ("Plantation Grande Reserve", "Spirituosen"),
        ("Diplomatico Reserva Exclusiva", "Spirituosen"),
        ("Matusalem Gran Reserva 15", "Spirituosen"),
        ("Pyrat XO Reserve", "Spirituosen"),
        ("Myers's Rum Dark", "Spirituosen"),
        ("Old Pascas 73%", "Spirituosen"),
        ("Tanqueray No. Ten", "Spirituosen"),
        ("Bombay Bramble", "Spirituosen"),
        ("Brockmans Gin", "Spirituosen"),
        ("Nordés Gin", "Spirituosen"),
        ("Patrón Silver Tequila", "Spirituosen"),
        ("Patrón Reposado Tequila", "Spirituosen"),
        ("Patrón Añejo Tequila", "Spirituosen"),
        ("Don Julio 1942", "Spirituosen"),
        ("1800 Tequila Silver", "Spirituosen"),
        ("1800 Tequila Reposado", "Spirituosen"),
        ("San Cosme Mezcal", "Spirituosen"),
        ("Mezcal Verde Momento", "Spirituosen"),
        ("Averna Amaro", "Spirituosen"),
        ("Montenegro Amaro", "Spirituosen"),
        ("Tia Maria Kaffeelikör", "Spirituosen"),
        ("Grand Marnier", "Spirituosen"),
        ("Triple Sec", "Spirituosen"),
        ("Disaronno Amaretto", "Spirituosen"),
        ("Frangelico Haselnusslikör", "Spirituosen"),
        ("Chambord Himbeerlikör", "Spirituosen"),
        ("Kleiner Feigling", "Spirituosen"),
        ("Xuxu Erdbeerlikör", "Spirituosen"),
        ("Batida de Côco", "Spirituosen"),
        ("Passoa Maracujalikör", "Spirituosen"),
        ("Veuve Clicquot Champagne", "Wein"),
        ("Corona Extra", "Bier"),
        ("Bitburger Alkoholfrei", "Bier"),
        ("Heineken Pils", "Bier"),
        ("Warsteiner Pils", "Bier"),
        ("Arcobräu Mooser Liesl Helles", "Bier"),
        ("Beck's Pils", "Bier"),
        ("Krombacher Pils", "Bier"),
        ("Augustiner Lagerbier Hell", "Bier"),
        ("Paulaner Hefeweizen", "Bier"),
        ("Erdinger Weißbier", "Bier"),
        ("Astra Urtyp", "Bier"),
        ("Desperados", "Bier"),
        ("Salitos Tequila Beer", "Bier"),
        ("Gösser Naturradler", "Bier"),
        ("Schöfferhofer Grapefruit", "Bier"),
        ("Guinness Extra Stout", "Bier"),
        ("Franziskaner Weissbier", "Bier"),
        ("Rothaus Tannenzäpfle", "Bier"),
        ("Tegernseer Hell", "Bier"),
        ("Jever Pilsener", "Bier"),
        ("Radeberger Pilsner", "Bier"),
        ("Flensburger Pilsener", "Bier"),
        ("Schneider Weisse", "Bier"),
        ("Veltins Pilsener", "Bier"),
        ("Coke", "Softdrinks"),
        ("Fanta", "Softdrinks"),
        ("Sprite", "Softdrinks"),
        ("Heil Apfelsaft", "Softdrinks"),
        ("Heil Orangensaft", "Softdrinks"),
        ("Coca-Cola Zero", "Softdrinks"),
        ("Mezzo Mix", "Softdrinks"),
        ("Paulaner Spezi", "Bier"),
        ("Red Bull Energy Drink", "Softdrinks"),
        ("Monster Energy", "Softdrinks"),
        ("28 Black Energy", "Softdrinks"),
        ("Schweppes Tonic Water", "Softdrinks"),
        ("Schweppes Bitter Lemon", "Softdrinks"),
        ("Schweppes Ginger Ale", "Softdrinks"),
        ("Thomas Henry Ginger Beer", "Softdrinks"),
        ("Thomas Henry Tonic Water", "Softdrinks"),
        ("San Pellegrino Mineralwasser", "Softdrinks"),
        ("Gerolsteiner Sprudel", "Softdrinks"),
        ("Volvic Stilles Wasser", "Softdrinks"),
        ("Vöslauer Mineralwasser", "Softdrinks"),
        ("Club Mate", "Softdrinks"),
        ("Granini Ananassaft", "Softdrinks"),
        ("Granini Cranberrysaft", "Softdrinks"),
        ("Granini Maracujasaft", "Softdrinks"),
        ("Elephant Bay Ice Tea", "Softdrinks"),
        ("Absolut Vodka", "Spirituosen"),
        ("Smirnoff Red Label", "Spirituosen"),
        ("Grey Goose Vodka", "Spirituosen"),
        ("Belvedere Vodka", "Spirituosen"),
        ("Three Sixty Vodka", "Spirituosen"),
        ("Wodka Gorbatschow", "Spirituosen"),
        ("Finlandia Vodka", "Spirituosen"),
        ("Russian Standard Vodka", "Spirituosen"),
        ("Jack Daniel's Old No. 7", "Spirituosen"),
        ("Jim Beam White Label", "Spirituosen"),
        ("Jameson Irish Whiskey", "Spirituosen"),
        ("Johnnie Walker Red Label", "Spirituosen"),
        ("Johnnie Walker Black Label", "Spirituosen"),
        ("Maker's Mark Bourbon", "Spirituosen"),
        ("Tullamore D.E.W.", "Spirituosen"),
        ("Jack Daniel's Tennessee Honey", "Spirituosen"),
        ("Ballantine's Finest", "Spirituosen"),
        ("Chivas Regal 12 Jahre", "Spirituosen"),
        ("Glenfiddich 12 Jahre", "Spirituosen"),
        ("Havana Club 3 Años", "Spirituosen"),
        ("Havana Club 7 Años", "Spirituosen"),
        ("Captain Morgan Spiced Gold", "Spirituosen"),
        ("Bacardi Carta Blanca", "Spirituosen"),
        ("Bacardi Carta Negra", "Spirituosen"),
        ("Don Papa Rum", "Spirituosen"),
        ("Ron Zacapa 23", "Spirituosen"),
        ("Botucal Reserva Exclusiva", "Spirituosen"),
        ("Malibu Kokoslikör", "Spirituosen"),
        ("Tanqueray London Dry Gin", "Spirituosen"),
        ("Bombay Sapphire Gin", "Spirituosen"),
        ("Hendrick's Gin", "Spirituosen"),
        ("Monkey 47 Schwarzwald Dry Gin", "Spirituosen"),
        ("Gin Sul", "Spirituosen"),
        ("Gordon's London Dry Gin", "Spirituosen"),
        ("Gordon's Premium Pink Gin", "Spirituosen"),
        ("The Botanist Islay Dry Gin", "Spirituosen"),
        ("Sierra Tequila Silver", "Spirituosen"),
        ("Sierra Tequila Reposado", "Spirituosen"),
        ("Jose Cuervo Especial Silver", "Spirituosen"),
        ("Jose Cuervo Especial Reposado", "Spirituosen"),
        ("Olmeca Blanco Tequila", "Spirituosen"),
        ("Don Julio Blanco", "Spirituosen"),
        ("Jägermeister", "Spirituosen"),
        ("Berliner Luft", "Spirituosen"),
        ("Sambuca Molinari", "Spirituosen"),
        ("Baileys Irish Cream", "Spirituosen"),
        ("Aperol", "Spirituosen"),
        ("Campari", "Spirituosen"),
        ("Lillet Blanc", "Spirituosen"),
        ("Ramazzotti Amaro", "Spirituosen"),
        ("Fernet-Branca", "Spirituosen"),
        ("Rotkäppchen Sekt Trocken", "Wein"),
        ("Henkell Trocken", "Wein"),
        ("Moët & Chandon Impérial Champagner", "Wein"),
        ("Freixenet Cava", "Wein"),
        ("Lugana Weißwein", "Wein"),
        ("Riesling Trocken", "Wein"),
        ("Grauburgunder", "Wein"),
        ("Primitivo di Manduria", "Wein"),
        ("Merlot Rotwein", "Wein"),
        ("Whispering Angel Rosé", "Wein"),
    };
}
